public:

/*!@brief Read file and try to interpret it as an instance of `PlanarDiagram`.
 *
 * CAUTION: This uses a parser that takes everything very literal. For example, reading will fail if any separator does not exactly match the expectations. Additional whitespace will _not_ be ignored and lead to failure. Better use this only on files generated by `WriteToFile` and only for the same class.
 *
 * CAUTION: The internal data layout may change over time. We give little guarantees that this i/o interface is stable over various versions of `Knoodle`. It is mostly meant for debugging. Use `PDCode` or `MacLeodCode` to store/retrieve data suitable for long-term storage.
 */
static PD_T FromFile( cref<std::filesystem::path> file )
{
    Tools::InString s (file);

    return FromInString(s);
}


/*!@brief Read from `InString` and try to interpret it as an instance of `PlanarDiagram`.
 *
 * CAUTION: This is a very literal parser. For example, reading will fail if any separator does not exactly match the expectations. Additional whitespace will _not_ be accepted and lead to failure. Better use this only on strings originally generated by `WriteToString` and only for the same class `PlanarDiagram` as the integer type `PlanarDiagram::Int` matters for the interpretation.
 *
 * CAUTION: The internal data layout may change over time. We give little guarantees that this i/o interface is stable over various versions of `Knoodle`. It is mostly meant for debugging. Use `PDCode` or `MacLeodCode` to store/retrieve data suitable for long-term storage.
 */
static PD_T FromInString( mref<Tools::InString> s )
{
    // needs to know all member variables
    
    // Using 1-byte separators that are compatible with Mathematica and that minimize string size.
    constexpr char prefix [2] = "{";
    constexpr char infix  [2] = ",";
    constexpr char suffix [2] = "}";
    
    if( s.FailedQ() )
    {
        Msgr::eprint("FromInString", ": InString is in failure state. Returning invalid diagram.");
        return PD_T::InvalidDiagram();
    }
    
    Int max_crossing_count;
    
    const auto name = ClassName();
    
    s.SkipChars(&name[0],name.size());
    if( s.FailedQ() )
    {
        Msgr::eprint("FromInString",": InString does not start with \"", name, "\". Returning invalid diagram. Maybe there is a type mismatch. Returning invalid diagram.");
        return PD_T::InvalidDiagram();
    }
    
    s.SkipChars("\nmax_crossing_count = ");
    s.Take(max_crossing_count);
    
    if( s.FailedQ() )
    {
        Msgr::eprint("FromInString", ": Failed to read max_crossing_count. Returning invalid diagram.");
        return PD_T::InvalidDiagram();
    }
    
    PD_T pd ( max_crossing_count, true );
    
    const Int n = pd.max_crossing_count;
    const Int m = pd.max_arc_count;
    
    s.SkipChars("\ncrossing_count = ");
    s.Take(pd.crossing_count);
    s.SkipChars("\nmax_arc_count = ");
    s.Take(pd.max_arc_count);
    s.SkipChars("\narc_count = ");
    s.Take(pd.arc_count);
    
    // Know the array sizes in advance, we can put the data directly into pd, avoiding further allocations and copying.
    s.SkipChars("\nC_arcs = ");
    s.TakeArray(pd.C_arcs.WriteAccess(),
        n     , prefix, infix, suffix,
        Int{2}, prefix, infix, suffix,
        Int{2}, prefix, infix, suffix
    );
    s.SkipChars("\nC_state = ");
    s.TakeArray(pd.C_state.WriteAccess(), n, prefix, infix, suffix);
    
    s.SkipChars("\nA_cross = ");
    s.TakeArray(pd.A_cross.WriteAccess(),
        m     , prefix, infix, suffix,
        Int{2}, prefix, infix, suffix
    );
    s.SkipChars("\nA_state = ");
    s.TakeArray(pd.A_state.WriteAccess(), m, prefix, infix, suffix);
    s.SkipChars("\nA_color = ");
    s.TakeArray(pd.A_color.WriteAccess(), m, prefix, infix, suffix);
    s.SkipChars("\nlast_color_deactivated = ");
    s.Take(pd.last_color_deactivated);
    s.SkipChars("\nproven_minimalQ = ");
    s.Take(pd.proven_minimalQ);
    s.SkipChar('\n');
    
    if( s.FailedQ() )
    {
        Msgr::eprint("FromInString", ": Failed to read from InString. Returning invalid diagram.");
        return PD_T::InvalidDiagram();
    }
    
    return pd;
}

/*!@brief Import from `InString`, using default options.*/
friend InString & operator>>( InString & s, PD_T & pd )
{
    pd = PD_T::FromInString(s);
    return s;
}

///*!@brief Import from `std::basic_istream`, using default options.*/
//template<typename C, typename T>
//friend std::basic_istream<C,T> & operator>>(
//    std::basic_istream<C,T> & stream, const PD_T & pd
//)
//{
//    InString s;
//    s << stream
//    s >> pd;
//    return stream;
//}
