#pragma once

#include "KnotInvariants/Alexander_UMFPACK.hpp"

namespace Knoodle
{
    /*! The purpose of this class is to load pd diagrams generated by plantri and to filter out only those that are already minimal. This helps to generate the data underlying Klut.
     */
    
    template<IntQ Int_ = Int32>
    class Klutter2 final
    {
    public:
    
        using Int             = Int_;
        using Klut_T          = Klut;
        using PDC_T           = PlanarDiagramComplex<Int>;
        using PD_T            = PDC_T::PD_T;
        using Reapr_T         = PDC_T::Reapr_T;
        using LinkEmbedding_T = Reapr_T::LinkEmbedding_T;
        using Compaction_T    = PDC_T::OrthoDraw_T::CompactionMethod_T;

        static constexpr Size_T max_crossing_count = Klut_T::max_crossing_count;
        
        using CodeInt = Klut_T::CodeInt;
        
        // During generation of the table we need to store way more things than just the knot classes in the lookup table.
        using ID_T   = Size_T;
        static constexpr ID_T not_found = std::numeric_limits<ID_T>::max();
        
        static constexpr bool debugQ = false;
//        static constexpr bool debugQ = true;
        
        static constexpr Size_T KeyLength = Klut_T::KeyLength;
        using KeyEntry_T  = Klut_T::KeyEntry_T;
        using Key_T       = Klut_T::Key_T;
        using KeySet_T    = Klut_T::KeySet_T;
        using LUT_T       = Klut_T::LUT_T;
        using Path_T      = Klut_T::Path_T;
        using Name_T      = Klut_T::Name_T;
        
        static constexpr Key_T InvalidKey = Klut_T::InvalidKey;
        
        using Invariant_T = Size_T;
        
        enum class Flag_T : int
        {
            NoChange               = 0,
            Changed                = 1,
            Identified             = 2,
            SimplerDiagramDetected = 3,
            Failure                = -1
            
        };
        
#include "Klutter2/Classifier.hpp"
#include "Klutter2/Subklutter.hpp"
        
    private:
        
        Path_T working_directory;
        Path_T target_directory;
        Int crossing_count = 0;
        Size_T thread_count = 1;
        
        Reapr_T::Settings_T reapr_settings {
            .permute_randomQ     = true,
    //        .energy              = args.energy,
            .ortho_draw_settings = {
                .randomize_bends          = 2,
                .randomize_virtual_edgesQ = true,
                .compaction_method        = Compaction_T::TopologicalNumbering,
    //        .compaction_method        = Compaction_T::LengthMCF,
            },
            .scaling             = 3.
        };
        
        std::vector<Reapr_T> reaprs;
        
//        LUT_T lut;
        std::vector<Name_T>   names;
//        std::vector<KeySet_T> buckets;
        
        std::vector<Subklutter> subklutters;
        AssociativeContainer<Invariant_T,Size_T> I_S;
        
        Size_T max_bucket_count = 0;
        Size_T max_name_size    = 0;
        
        bool failedQ = false;
        bool knot_info_loadedQ = false;
        bool plantri_loadedQ = false;
        
    public:
        
        Klutter2() = default;
        
        template<IntQ ExtInt, IntQ ExtInt2>
        Klutter2(
            cref<Path_T> working_directory_,
            cref<Path_T> target_directory_,
            const ExtInt crossing_count_,
            const ExtInt2 thread_count_
        )
        :   working_directory { working_directory_                     }
        ,   target_directory  { target_directory_                      }
        ,   crossing_count    { int_cast<Int>(crossing_count_)         }
        ,   thread_count      { Max(Size_T(1),ToSize_T(thread_count_)) }
        ,   reaprs            { thread_count, reapr_settings }
        {
            if( std::cmp_greater(crossing_count,max_crossing_count) )
            {
                eprint(MethodName("Reset")+": Only works for 64 crossings or less.");
                crossing_count = 0;
            }
        }

        Int CrossingCount() const
        {
            return crossing_count;
        }
        
        Size_T ThreadCount() const
        {
            return thread_count;
        }
        
        cref<Path_T> WorkingDirectory() const
        {
            return working_directory;
        }

        Size_T KnotTypeCount() const
        {
            return names.size();
        }
        
        Size_T CodeSize() const
        {
            return Size_T(crossing_count);
        }

        Size_T SubklutterCount() const
        {
            return subklutters.size();
        }
        
        // TODO:
//        Size_T KeyCount() const
//        {
//            return lut.size();
//        }
        
        Size_T MaxNameSize() const
        {
            return max_name_size;
        }
        
        bool KnotInfoLoadedQ() const
        {
            return knot_info_loadedQ;
        }
        
        bool PlantriLoadedQ() const
        {
            return plantri_loadedQ;
        }
        
        Tensor2<Size_T,Size_T> InvariantsToSubklutters()
        {
            Tensor2<Size_T,Size_T> a( I_S.size(), Size_T(2) );
            
            Size_T i = 0;
            
            for( auto & x : I_S )
            {
                a(i,0) = x.first;
                a(i,1) = x.second;
                ++i;
            }
            
            return a;
        }
        
        
        Size_T IdentifiedKeyCount() const
        {
            Size_T sum = 0;
            
            for( const auto & subklutter : subklutters )
            {
                sum += subklutter.IdentifiedKeyCount();
            }
            return sum;
        }
        
        Size_T UnidentifiedKeyCount() const
        {
            Size_T sum = 0;
            
            for( const auto & subklutter : subklutters )
            {
                sum += subklutter.UnidentifiedKeyCount();
            }
            return sum;
        }
        
        
        
        // TODO: Implement this.
        
//        template<IntQ ExtInt>
//        void WriteCodes( mptr<ExtInt> output ) const
//        {
//            Size_T i = 0;
//
//            for( const auto & x : lut )
//            {
//                KeyToMacLeodCode( x.first, &output[crossing_count * i] );
//                ++i;
//            }
//        }
  
        // TODO: Implement this.
        
//        template<typename ExtInt = Int>
//        Tensor2<ExtInt,Size_T> Codes() const
//        {
//            TOOLS_PTIMER(timer,MethodName("Codes"));
//
//            Tensor2<ExtInt,Size_T> output ( KeyCount(), CodeSize() );
//
//            WriteCodes(output.data());
//
//            return output;
//        }
        
        // TODO: Implement this.
        
//        template<IntQ ExtInt>
//        void WriteIds( mptr<ExtInt> output ) const
//        {
//            Size_T i = 0;
//
//            for( const auto & x : lut )
//            {
//                output[i] = x.second;
//                ++i;
//            }
//        }

        // TODO: Implement this.
        
//        template<typename ExtInt = ID_T>
//        Tensor1<ExtInt,Size_T> Ids() const
//        {
//            TOOLS_PTIMER(timer,MethodName("Ids"));
//
//            Tensor1<ExtInt,Size_T> output ( KeyCount() );
//
//            WriteIds(output.data());
//
//            return output;
//        }
        
        // TODO: Implement this.
        
//        template<IntQ ExtInt>
//        void WriteIdentifiedCodes( mptr<ExtInt> output ) const
//        {
//            Size_T i = 0;
//
//            Size_T code_size = CodeSize();
//            
//            for( ID_T id = 0; id < KnotTypeCount(); ++id )
//            {
//                for( const Key_T & key : buckets[id] )
//                {
//                    KeyToMacLeodCode( key, &output[code_size * i] );
//                    ++i;
//                }
//            }
//        }

        // TODO: Implement this.
        
//        template<typename ExtInt = Int>
//        Tensor2<ExtInt,Size_T> IdentifiedCodes() const
//        {
//            TOOLS_PTIMER(timer,MethodName("IdentifiedCodes"));
//
//            Tensor2<ExtInt,Size_T> output ( IdentifiedKeyCount(), CodeSize() );
//
//            WriteIdentifiedCodes(output.data());
//
//            return output;
//        }
        
    
        
        // TODO: Implement this.
        
//        template<IntQ ExtInt>
//        void WriteUnidentifiedCodes( mptr<ExtInt> output ) const
//        {
//            Size_T i = 0;
//            
//            Size_T code_size = CodeSize();
//
//            for( ID_T id = KnotTypeCount(); id < buckets.size(); ++id )
//            {
//                for( const Key_T & key : buckets[id] )
//                {
//                    KeyToMacLeodCode( key, &output[code_size * i] );
//                    ++i;
//                }
//            }
//        }
        
        // TODO: Implement this.

//        template<typename ExtInt = Int>
//        Tensor2<ExtInt,Size_T> UnidentifiedCodes() const
//        {
//            TOOLS_PTIMER(timer,MethodName("UnidentifiedCodes"));
//
//            Tensor2<ExtInt,Size_T> output ( UnidentifiedKeyCount(), CodeSize() );
//
//            WriteUnidentifiedCodes(output.data());
//
//            return output;
//        }

        bool FailedQ() const
        {
            return failedQ;
        }
        
        bool SucceededQ() const
        {
            return !failedQ && knot_info_loadedQ && plantri_loadedQ && (UnidentifiedKeyCount() == Size_T(0));
        }

        
    public:
        
#include "Klutter2/Key.hpp"
#include "Klutter2/KnotInfo.hpp"
#include "Klutter2/Plantri.hpp"
#include "Klutter2/Export.hpp"
        
        
        // Not needed.
        Flag_T GenerateIdentified(
            const Size_T embedding_trials,
            const Size_T rotation_trials
        )
        {
            [[maybe_unused]] auto tag = [](){ return MethodName("GenerateIdentified"); };

            if( !knot_info_loadedQ )
            {
                wprint(tag() + ": No data from KnotInfo loaded, yet. Call LoadKnotInfo first.");
                return Flag_T::NoChange;
            }
            
            Flag_T flag = Flag_T::NoChange;
            
            // DEBUGGING
            logprint(tag());
            
            ThreadTensor2<double,Size_T> thread_time ( thread_count, 1, 0. );
            ThreadTensor2<Size_T,Size_T> thread_info ( thread_count, 1, Size_T(0) );
            
//            tic(tag());
            Do<Parallel,Dynamic>(
                [this,embedding_trials,rotation_trials,&thread_time,&thread_info]( Size_T thread, Size_T idx )
                {
                    TimeInterval thread_timer;
                    thread_timer.Tic();
                
                    mref<Reapr_T> reapr = reaprs[thread];
                    // TODO: Message passing.
                    (void)subklutters[idx].GenerateIdentified(reapr, embedding_trials, rotation_trials );
                    
                    thread_timer.Toc();
                    thread_time(thread,0) += thread_timer.Duration();
                    ++thread_info(thread,0);
                },
                subklutters.size(), thread_count
            );
//            toc(tag());
            
            for( Size_T thread = 0; thread < thread_count; ++thread )
            {
                logprint(tag() + ": thread " + ToString(thread) + " time = " + ToString(thread_time(thread,Size_T(0))) + "; job_count = " + ToString(thread_info(thread,Size_T(0)))+ "." );
            }
            
            return flag;
        }

        Flag_T GenerateUnidentified(
            const Size_T embedding_trials,
            const Size_T rotation_trials
        )
        {
            [[maybe_unused]] auto tag = [](){ return MethodName("GenerateUnidentified"); };
            
            if( !knot_info_loadedQ )
            {
                wprint(tag() + ": No data from KnotInfo loaded, yet. Call LoadKnotInfo first.");
                return Flag_T::NoChange;
            }
            
            if( !plantri_loadedQ )
            {
                wprint(tag() + ": No pd codes from plantri loaded, yet. Call LoadPlantriPDCodes first.");
                return Flag_T::NoChange;
            }
            
            Flag_T flag = Flag_T::NoChange;
            
            // DEBUGGING
            logprint(tag());
            
            ThreadTensor2<double,Size_T> thread_time ( thread_count, 1, 0. );
            ThreadTensor2<Size_T,Size_T> thread_info ( thread_count, 1, Size_T(0) );
            
//            tic(tag());
            Do<Parallel,Dynamic>(
                [this,embedding_trials,rotation_trials,&thread_time,&thread_info]( Size_T thread, Size_T idx )
                {
                    TimeInterval thread_timer;
                    thread_timer.Tic();
                    
                    mref<Reapr_T> reapr = reaprs[thread];
                    // TODO: Message passing.
                    (void)subklutters[idx].GenerateUnidentified(reapr, embedding_trials, rotation_trials );
                    
                    thread_timer.Toc();
                    thread_time(thread,0) += thread_timer.Duration();
                    ++thread_info(thread,0);
                },
                subklutters.size(), thread_count
            );
//            toc(tag());
            
            for( Size_T thread = 0; thread < thread_count; ++thread )
            {
                logprint(tag() + ": thread " + ToString(thread) + " time = " + ToString(thread_time(thread,Size_T(0))) + "; job_count = " + ToString(thread_info(thread,Size_T(0)))+ "." );
            }
            
            return flag;
        }
        
        
//        bool Compute(
//            const Size_T max_iter         = 1000,
//            const Size_T embedding_trials = 20,
//            const Size_T rotation_trials  = 20
//        )
//        {
//            [[maybe_unused]] auto tag = [](){ return MethodName("Compute"); };
//
//            if( !knot_info_loadedQ )
//            {
//                wprint(tag() + ": No data from KnotInfo loaded, yet. Call LoadKnotInfo first.");
//                return false;
//            }
//            
//            if( !plantri_loadedQ )
//            {
//                wprint(tag() + ": No pd codes from plantri loaded, yet. Call LoadPlantriPDCodes first.");
//                return false;
//            }
//            
//            // DEBUGGING
//            logprint(tag());
//            
//            ThreadTensor2<double,Size_T> thread_time ( thread_count, 1, 0. );
//            ThreadTensor2<Size_T,Size_T> thread_info ( thread_count, 2, Size_T(0) );
//            
//            for( Size_T thread = 0; thread < thread_count; ++thread )
//            {
//                thread_info(thread,1) = Size_T(true);
//            }
//            
//            tic(tag());
//            Do<Parallel,Dynamic>(
//                [this,max_iter,embedding_trials,rotation_trials,&thread_time,&thread_info]( Size_T thread, Size_T idx )
//                {
//                    TimeInterval thread_timer;
//                    thread_timer.Tic();
//                    
//                    mref<Reapr_T> reapr = reaprs[thread];
//                    
//                    bool succeededQ = subklutters[idx].Compute(
//                        reapr, max_iter, embedding_trials, rotation_trials
//                    );
//                    
//                    thread_timer.Toc();
//                    thread_time(thread,Size_T(0)) += thread_timer.Duration();
//                    thread_info(thread,Size_T(0)) += Size_T(1);
//                    thread_info(thread,Size_T(1)) &= Size_T(succeededQ);
//                },
//                subklutters.size(), thread_count
//            );
//            toc(tag());
//            
//            bool succeededQ = true;
//            
//            for( Size_T thread = 0; thread < thread_count; ++thread )
//            {
//                logprint(tag() + ": thread " + ToString(thread) + " time = " + ToString(thread_time(thread,Size_T(0))) + "; job_count = " + ToString(thread_info(thread,Size_T(0))) + "." );
//                
//                succeededQ = succeededQ && (thread_info(thread,Size_T(1)) == Size_T(1));
//            }
//            
//            return succeededQ;
//        }
        
    public:
        
        static std::string MethodName( const std::string & tag )
        {
            return ClassName() + "::" + tag;
        }
        
        static std::string ClassName()
        {
            return std::string("Klutter2")
            + "<" + TypeName<Int>
            + ">";
        }
        
    }; // class Klutter2
    
} // namespace Knoodle

