#pragma once

namespace Knoodle
{
    /*! The purpose of this class is to load pd diagrams generated by plantri and to filter out only those that are already minimal. This helps to generate the data underlying PrimeKnotLookupTable.
     */
    
    template<IntQ Int_ = Int32>
    class Klutter final
    {
    public:
    
        using Int             = Int_;
        using Klut_T          = Klut;
        using PDC_T           = PlanarDiagramComplex<Int>;
        using PD_T            = PDC_T::PD_T;
        using Reapr_T         = PDC_T::Reapr_T;
        using LinkEmbedding_T = Reapr_T::LinkEmbedding_T;
        using Compaction_T    = PDC_T::OrthoDraw_T::CompactionMethod_T;

        static constexpr Size_T max_crossing_count = Klut_T::max_crossing_count;
        
        using CodeInt = Klut_T::CodeInt;
        
        // During generation of the table we need to store way more things than just the knot classes in the lookup table.
        using ID_T   = Size_T;
        static constexpr ID_T not_found = std::numeric_limits<ID_T>::max();
        
        static constexpr bool debugQ = false;
//        static constexpr bool debugQ = true;
        
        static constexpr Size_T KeyLength = Klut_T::KeyLength;
        using KeyEntry_T  = Klut_T::KeyEntry_T;
        using Key_T       = Klut_T::Key_T;
        using Hash_T      = Klut_T::Hash_T;
        using KeySet_T    = Klut_T::KeySet_T;
        using LUT_T       = Klut_T::LUT_T;
        using Path_T      = Klut_T::Path_T;
        using Name_T      = Klut_T::Name_T;
        
        static constexpr Key_T InvalidKey = Klut_T::InvalidKey;
        
    private:
        
        Path_T working_directory;
        Path_T target_directory;
        Int crossing_count = 0;
        Size_T thread_count = 1;
        
        // After sieving has finished, these two subsets contain all the Keys for diagrams that belong to a prime knot with crossing_count crossings.
        KeySet_T unidentified_ralt_keys;
        KeySet_T unidentified_nalt_keys;
        
        LUT_T lut;
        std::vector<Name_T>   names;
        std::vector<KeySet_T> buckets;
        
//        Reapr_T::Settings_T reapr_settings ;
        
        Reapr_T R {{
            .permute_randomQ     = true,
//                .energy              = args.energy,
            .ortho_draw_settings = {
                .randomize_bends          = 2,
                .randomize_virtual_edgesQ = true,
                .compaction_method        = Compaction_T::TopologicalNumbering,
//                    .compaction_method        = Compaction_T::LengthMCF,
            },
            .scaling             = 3.
        }};
        
        Size_T max_bucket_count = 0;
        
        bool failedQ = false;
        bool knot_info_loadedQ = false;
        bool plantri_loadedQ = false;
        
    public:
        
        Klutter() = default;
        
        template<IntQ ExtInt, IntQ ExtInt2>
        Klutter(
            cref<Path_T> working_directory_,
            cref<Path_T> target_directory_,
            const ExtInt crossing_count_,
            const ExtInt2 thread_count_
        )
        :   working_directory { working_directory_                     }
        ,   target_directory  { target_directory_                      }
        ,   crossing_count    { int_cast<Int>(crossing_count_)         }
        ,   thread_count      { Max(Size_T(1),ToSize_T(thread_count_)) }
        {
            if( std::cmp_greater(crossing_count,max_crossing_count) )
            {
                eprint(MethodName("Reset")+": Only works for 64 crossings or less.");
                crossing_count = 0;
            }
        }

        Int CrossingCount() const
        {
            return crossing_count;
        }
        
        Size_T ThreadCount() const
        {
            return thread_count;
        }
        
        cref<Path_T> WorkingDirectory() const
        {
            return working_directory;
        }

        Size_T KnotTypeCount() const
        {
            return names.size();
        }
        
        Size_T CodeSize() const
        {
            return Size_T(crossing_count);
        }

        Size_T KeyCount() const
        {
            return lut.size();
        }
        
        template<IntQ ExtInt>
        void WriteCodes( mptr<ExtInt> output ) const
        {
            Size_T i = 0;

            for( const auto & x : lut )
            {
                KeyToMacLeodCode( x.first, &output[crossing_count * i] );
                ++i;
            }
        }
        
        template<typename ExtInt = Int>
        Tensor2<ExtInt,Size_T> Codes() const
        {
            TOOLS_PTIMER(timer,MethodName("Codes"));

            Tensor2<ExtInt,Size_T> output ( KeyCount(), CodeSize() );

            WriteCodes(output.data());

            return output;
        }
        
        template<IntQ ExtInt>
        void WriteIds( mptr<ExtInt> output ) const
        {
            Size_T i = 0;

            for( const auto & x : lut )
            {
                output[i] = x.second;
                ++i;
            }
        }
        
        template<typename ExtInt = ID_T>
        Tensor1<ExtInt,Size_T> Ids() const
        {
            TOOLS_PTIMER(timer,MethodName("Ids"));

            Tensor1<ExtInt,Size_T> output ( KeyCount() );

            WriteIds(output.data());

            return output;
        }
        
        
        Size_T IdentifiedKeyCount() const
        {
            Size_T sum = 0;
            
            for( ID_T id = 0; id < KnotTypeCount(); ++id )
            {
                sum += buckets[id].size();
            }
            return sum;
        }
        
        template<IntQ ExtInt>
        void WriteIdentifiedCodes( mptr<ExtInt> output ) const
        {
            Size_T i = 0;

            Size_T code_size = CodeSize();
            
            for( ID_T id = 0; id < KnotTypeCount(); ++id )
            {
                for( const Key_T & key : buckets[id] )
                {
                    KeyToMacLeodCode( key, &output[code_size * i] );
                    ++i;
                }
            }
        }

        template<typename ExtInt = Int>
        Tensor2<ExtInt,Size_T> IdentifiedCodes() const
        {
            TOOLS_PTIMER(timer,MethodName("IdentifiedCodes"));

            Tensor2<ExtInt,Size_T> output ( IdentifiedKeyCount(), CodeSize() );

            WriteIdentifiedCodes(output.data());

            return output;
        }
        
        
        Size_T UnidentifiedKeyCount() const
        {
            Size_T sum = 0;
            
            for( ID_T id = KnotTypeCount(); id < buckets.size(); ++id )
            {
                sum += buckets[id].size();
            }
            return sum;
        }
        
        template<IntQ ExtInt>
        void WriteUnidentifiedCodes( mptr<ExtInt> output ) const
        {
            Size_T i = 0;
            
            Size_T code_size = CodeSize();

            for( ID_T id = KnotTypeCount(); id < buckets.size(); ++id )
            {
                for( const Key_T & key : buckets[id] )
                {
                    KeyToMacLeodCode( key, &output[code_size * i] );
                    ++i;
                }
            }
        }

        template<typename ExtInt = Int>
        Tensor2<ExtInt,Size_T> UnidentifiedCodes() const
        {
            TOOLS_PTIMER(timer,MethodName("UnidentifiedCodes"));

            Tensor2<ExtInt,Size_T> output ( UnidentifiedKeyCount(), CodeSize() );

            WriteUnidentifiedCodes(output.data());

            return output;
        }


        Tensor1<Size_T,Size_T> BucketSizes() const
        {
            Tensor1<Size_T,Size_T> sizes ( buckets.size() );
            
            for( ID_T id = 0; id < buckets.size(); ++id )
            {
                sizes[id] = buckets[id].size();
            }
            return sizes;
        }
        
        
        Size_T BucketCount() const
        {
            return buckets.size();
        }
        
        Size_T MaxBucketCount() const
        {
            return max_bucket_count;
        }
        
        Size_T ActiveBucketCount() const
        {
            Size_T bucket_count = 0;
            
            for( const auto & bucket : buckets )
            {
                if( bucket.size()  > Size_T(0) ) { ++bucket_count; }
            }
            return bucket_count;
        }
        
        bool BucketsOkayQ()
        {
            for( ID_T id = 0; id < buckets.size(); ++id )
            {
                for( const Key_T & key : buckets[id] )
                {
                    if( !lut.contains(key) )
                    {
                        eprint(MethodName("BucketsOkayQ")+ ": Bucket " + ToString(id) + " contains key " + std::string(ToString(key)) + ", but key is not registered in lut.");
                        failedQ = true;
                        return false;
                    }
                    
                    if( lut[key] != id )
                    {
                        eprint(MethodName("BucketsOkayQ")+ std::string(": Bucket ") + ToString(id) + " contains key " + std::string(ToString(key)) + ", but lut[key] = " + ToString(lut[key]) + ".");
                        failedQ = true;
                        return false;
                    }
                    
                    
                }
            }
            
            for( auto [key,id] : lut )
            {
                if( !buckets[id].contains(key) )
                {
                    eprint(MethodName("BucketsOkayQ")+ ": lut lists key " + std::string(ToString(key)) + " with id " + ToString(id) + ", but buckets[id] does not contain key.");
                    failedQ = true;
                    return false;
                }
            }
            
            return true;
        }

        bool FailedQ() const
        {
            return failedQ;
        }
        
        bool SucceededQ() const
        {
            return !failedQ && knot_info_loadedQ && plantri_loadedQ && (UnidentifiedKeyCount() == Size_T(0));
        }
        
    private:
        
        ID_T CreateBucket( cref<Key_T> key )
        {
            if constexpr ( debugQ )
            {
                logprint("CreateBucket(" + std::string(ToString(key)) + ")");
            }
            ID_T id = buckets.size();
            if constexpr ( debugQ )
            {
                logvalprint("created id",id);
            }
            buckets.emplace_back();
            buckets.back().insert(key);
            lut[key] = id;
            
            max_bucket_count = Max(max_bucket_count,buckets.size());
            
            return id;
        }
        
        template<bool cleanse_lutQ>
        void DeleteBucket( ID_T id )
        {
            if constexpr ( debugQ )
            {
                logprint(std::string("DeleteBucket<")+ToString(cleanse_lutQ)+">(" + ToString(id) + ")");
            }
            
            if( id < KnotTypeCount() )
            {
                wprint("Trying to delete bucket " + ToString(id) + ", which belongs to a knot class.");
                return;
            }
            
            if constexpr ( cleanse_lutQ )
            {
                for( const Key_T & key : buckets[id] )
                {
                    lut.erase(key);
                }
            }
            
            const ID_T p = id + ID_T(1);
            
            if( p == buckets.size() )
            {
                buckets.pop_back();
                while( !buckets.empty() && buckets.back().empty() )
                {
                    buckets.pop_back();
                }
            }
            else if( p < buckets.size() )
            {
                buckets[id] = KeySet_T();
            }
        }
        
        ID_T MergeBuckets( ID_T id_0, ID_T id_1 )
        {
            if constexpr ( debugQ )
            {
                logprint("MergeBuckets(" + ToString(id_0) + "," + ToString(id_1) + ")");
            }
            
            // We always merge into the smaller id.
            // We return the id of the persisting bucket.
            
            if( id_0 == id_1 ) { return id_0; }
            
            auto [i_0,i_1] = MinMax(id_0,id_1);
            
            if constexpr ( debugQ )
            {
                logvalprint("i_0",i_0);
                logvalprint("i_1",i_1);
                
//                // TODO: We might want to swap the buckets so that buckets[i_0] is the smaller bucket.
//                // TODO: Alas, we have to be careful: just swapping the buckets is not enough; we also have to edit the lut entries. Bad idea!
            }
            
            if constexpr ( debugQ )
            {
                logvalprint("buckets[i_0].size()",buckets[i_0].size());
                logvalprint("buckets[i_1].size()",buckets[i_1].size());
            }
            
            KeySet_T & bucket = buckets[i_0];
            
            for( const Key_T & key : buckets[i_1] )
            {
                if constexpr ( debugQ )
                {
                    logvalprint("key in bucket[i_1]",key);
                    logvalprint("lut[key]",lut[key]);
                }
                bucket.insert(key);
                lut[key] = i_0;
            }
            
            if constexpr ( debugQ )
            {
                logvalprint("i_0",i_0);
                logvalprint("i_1",i_1);
                logprint("DeleteBucket<false>(i_1);");
            }
            
            // We do not want to erase the lut-entries that belong to this bucket because we have already set them to th correct values.
            DeleteBucket<false>(i_1);
            
            return i_0;
        }
        
        bool AddKey( cref<Key_T> key, ID_T id )
        {
            if constexpr ( debugQ )
            {
                logprint("AddedKey(" + std::string(ToString(key)) + "," + ToString(id) + ")");
            }
            
            // TODO: Do we have to check the size of id?
            if( CrossingCount(key) <= crossing_count )
            {
                buckets[id].insert(key);
                lut[key] = id;
                return true;
            }
            else
            {
                if constexpr ( debugQ )
                {
                    logprint("CrossingCount(key) exceeds crossing_count. Key ignored.");
                }
                return false;
            }
        }
        
    public:
        
#include "Klutter/Key.hpp"
#include "Klutter/Symmetry.hpp"
#include "Klutter/KnotInfo.hpp"
#include "Klutter/Plantri.hpp"
#include "Klutter/Export.hpp"
        
    public:
        
        static std::string MethodName( const std::string & tag )
        {
            return ClassName() + "::" + tag;
        }
        
        static std::string ClassName()
        {
            return std::string("Klutter")
            + "<" + TypeName<Int>
            + ">";
        }
        
    }; // class Klutter
    
} // namespace Knoodle

